### PR TITLE
Fixing Documentation errors

### PR DESCRIPTION
**Pull request by Shashi456**
Looks like #275 didn't update a few places of the documentation to reflect dilation.

### CODE REVIEW

**Comment by jon-tow** [comment]
Hey @Shashi456 isn't it a bit redundant to summarize the layer by listing its initialization parameters?

**Comment by Shashi456** [comment]
@jon-tow I think so too on some level. But what i've discovered is we have documentation consistently for all the extension inits as well. Although i found it somewhat extensive and redundant initially, reading the docs i've discovered that it helps understand different types of initializations for layers.

**Comment by eaplatanios** [comment]
Personally I would rather not list all parameters in the summary. That's why they're document as arguments of the initializer anyway. Listing them is redundant and also makes the documentation harder to maintain, as also indicated by this PR. :)

**Comment by Shashi456** [comment]
@eaplatanios, I think the current norm as far as layers are concerned is to write description for every function. Since the docs generated from the files, have all functions including init. 

We could look at a format where in we avoid redundancy atleast in the parent layer functions by not describing the init since we already have parameter descriptions.

**Comment by Shashi456** [comment]
The error :
```
[3/39] Compiling TensorFlow Recurrent.swift
/swift-apis/Sources/TensorFlow/Layers/Recurrent.swift:267:58: error: value of type 'Cell.State' has no member 'withoutDerivative'
        return self(inputs, initialState: cell.zeroState.withoutDerivative())
```

**Comment by Shashi456** [comment]
Oh I'll have to merge master. Probably. Will do that in a second.

**Comment by rxwei** [comment]
Could you please do a pull from master?

**Comment by rxwei** [comment]
Yep, you beat me to it :)

**Comment by Shashi456** [comment]
Can this be merged?

**Pull request merged**
