### PR TITLE
Correcting argument order in assertEqual and XCTAssertEqual

### PR DESCRIPTION
**Pull request by Shashi456**
~There are some spacing issues in a few of the changes, I'll fix that soon.~ Done. 

A doubt I had was all XCTAssertEquals in LossTests have the expected before actual, Should i update that as well? 
I'd just like to get it right this time and reflect the changes across all files needed, So that we shouldn't have to refactor this repeatedly. 

Fix: #390 
cc: @rxwei

### CODE REVIEW

**Comment by eaplatanios** [comment]
@Shashi456 the loss tests are fixed in #356. I'll add documentation to finalize that PR today.

**Comment by Shashi456** [comment]
@eaplatanios sorry should've seen that.

**Comment by rxwei** [comment]
@Shashi456 Did you test locally?

**Comment by Shashi456** [comment]
@rxwei I didn't do it on the latest toolchain, I'll fix this asap.

**Comment by Shashi456** [comment]
@rxwei Fixed. Build and Test passes on latest nightly.

**Comment by Shashi456** [comment]
@eaplatanios could you also put a kokoro run on this ?

**Pull request merged**
