### PR TITLE
Test for conv2d

### PR DESCRIPTION
**Pull request by Shashi456**
Passes locally

### CODE REVIEW

**Comment by Shashi456** [comment]
@dan-zheng I wonder why Kokoro doesn't get triggered on my PRs.

**Comment by dan-zheng** [comment]
Kokoro CI runs automatically only on PRs created by people with push access, sorry!
Let's see if we can manually trigger CI.

**Comment by dan-zheng** [comment]
Thanks @Shashi456!

**Comment by Shashi456** [comment]
@dan-zheng, now comes the difficult part of choosing something to work on xD.

**Pull request merged**
