### PR TITLE
Revert "Revert SR-10697 workaround (#905)"

### PR DESCRIPTION
**Pull request by asuhan**
This reverts commit 5b24a71b3978717a95d07eeb597d2e63ffeb30e1.

### CODE REVIEW

**Comment by asuhan** [comment]
This breaks in Piper, revert for now. We can revisit this after the release.

**Comment by asuhan** [comment]
@dan-zheng It's not just that test, I only posted one failure. More tests fail for similar reasons.

**Comment by dan-zheng** [comment]
> @dan-zheng It's not just that test, I only posted one failure. More tests fail for similar reasons.

Thanks, updated my comment. Do you know why the failures weren't caught by Kokoro?

**Comment by asuhan** [comment]
@dan-zheng Because Kokoro doesn't test anything in Piper.

**Comment by ematejska** [comment]
Thanks for reverting?  I'll sync up offline about how to test/fix in Piper.

**Pull request merged**
