### PR TITLE
Add AdaMax optimizer

### PR DESCRIPTION
**Pull request by jon-tow**
Adds support for AdaMax (WIP). This is a reopening of a previous PR on a branch that was accidentally deleted #243.

### CODE REVIEW

**Comment by saeta** [comment]
#127

**Comment by rxwei** [comment]
Note: This PR didn't pass CI.

**Comment by Shashi456** [comment]
@rxwei you beat me to it, was just going to mention that :P

**Comment by saeta** [comment]
D'oh, sorry! :-(

**Comment by jon-tow** [comment]
Is there anything I can help with to have this pass CI?

**Comment by rxwei** [comment]
This has been fixed by upstream PRs. Thanks for asking!

**Comment by jon-tow** [comment]
No problem! Glad to hear it’s been resolved!

**Pull request merged**
