### PR TITLE
Switch to `func call` as call-syntax delegate method name.

### PR DESCRIPTION
**Pull request by dan-zheng**
Depends on: https://github.com/apple/swift/pull/24122.

### CODE REVIEW

**Comment by dan-zheng** [comment]
> Please also update tests.

Tests already use call-syntax as of https://github.com/tensorflow/swift-apis/pull/96.
Please let me know if I've missed anything. I'm building a toolchain now to verify `swift test` passes.

**Comment by rxwei** [comment]
> Tests already use call-syntax as of #96.

That's not quite the case: [[1]](https://github.com/tensorflow/swift-apis/blob/84f189ef01c30fea654d54326ae95876da82c9c4/Tests/DeepLearningTests/SequentialTests.swift#L27), [[2]](https://github.com/tensorflow/swift-apis/blob/84f189ef01c30fea654d54326ae95876da82c9c4/Tests/DeepLearningTests/TrivialModelTests.swift#L37), etc.

**Comment by dan-zheng** [comment]
> That's not quite the case: [[1]](https://github.com/tensorflow/swift-apis/blob/84f189ef01c30fea654d54326ae95876da82c9c4/Tests/DeepLearningTests/SequentialTests.swift#L27), [[2]](https://github.com/tensorflow/swift-apis/blob/84f189ef01c30fea654d54326ae95876da82c9c4/Tests/DeepLearningTests/TrivialModelTests.swift#L37), etc.

Fixed, thanks!

**Comment by dan-zheng** [comment]
Confirmed that `swift test` passes with toolchain built from https://github.com/apple/swift/pull/24122.
Merging.

**Pull request merged**
