### PR TITLE
Revert "Revert "[WIP] Add Dilation2D and Erosion2D layers""

### PR DESCRIPTION
**Pull request by saeta**
Reverts tensorflow/swift-apis#997

This rolls forward https://github.com/tensorflow/swift-apis/pull/989

### CODE REVIEW

**Comment by saeta** [comment]
@akshaan after fixing the CMake build, it looks like your changes are somehow not passing their own tests... I believe the [relevant portion of the logs](https://source.cloud.google.com/results/invocations/b1da986f-5cf0-47f7-85d9-6e532319b2da/targets/s4tf%2Fapis%2Fubuntu%2Fpresubmit/log) is:

```
/swift-apis/Tests/TensorFlowTests/LayerTests.swift:2513: error: LayerTests.testErosion2DGradient : XCTAssertEqual failed: ("[[[[-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-0.0, -0.0, -0.0, -0.0]],

  [[-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-0.0, -0.0, -0.0, -0.0]],

  [[-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0]],

  [[-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0]]],


 [[[-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-0.0, -0.0, -0.0, -0.0]],

  [[-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-1.0, -1.0, -1.0, -1.0],
   [-0.0, -0.0, -0.0, -0.0]],

  [[-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0]],

  [[-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0],
   [-0.0, -0.0, -0.0, -0.0]]]]") is not equal to ("[[[[1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [0.0, 0.0, 0.0, 0.0]],

  [[1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [0.0, 0.0, 0.0, 0.0]],

  [[0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0]],

  [[0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0]]],


 [[[1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [0.0, 0.0, 0.0, 0.0]],

  [[1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [0.0, 0.0, 0.0, 0.0]],

  [[0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0]],

  [[0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0, 0.0]]]]") -
/swift-apis/Tests/TensorFlowTests/LayerTests.swift:2556: error: LayerTests.testErosion2DGradient : XCTAssertEqual failed: ("[[[-12.0, -12.0, -12.0, -12.0],
  [ -0.0,  -0.0,  -0.0,  -0.0]],

 [[ -0.0,  -0.0,  -0.0,  -0.0],
  [ -0.0,  -0.0,  -0.0,  -0.0]],

 [[ -0.0,  -0.0,  -0.0,  -0.0],
  [ -0.0,  -0.0,  -0.0,  -0.0]]]") is not equal to ("[[[  0.0,   0.0,   0.0,   0.0],
  [  0.0,   0.0,   0.0,   0.0]],

 [[  0.0,   0.0,   0.0,   0.0],
  [  0.0,   0.0,   0.0,   0.0]],

 [[  0.0,   0.0,   0.0,   0.0],
  [-12.0, -12.0, -12.0, -12.0]]]") -
Test Case 'LayerTests.testErosion2DGradient' failed (0.003 seconds)
```

Do you think you could take a look to see what might be going wrong here?

Thanks!

**Comment by akshaan** [comment]
@saeta Yup my bad, I thought tests passed since CI checks looked good. I'll take a look and push a fix soon.

**Comment by akshaan** [comment]
Fix is up at #1008 @saeta

**Comment by saeta** [comment]
Thanks for #1008! I've now merged it in, and will re-run CI. (FWIW, I made the same mistake re: CI; all good!)

**Pull request merged**
