### PR TITLE
Disable failing BasicOperatortests.testVJPConcatentation.

### PR DESCRIPTION
**Pull request by bgogul**
Related to https://bugs.swift.org/browse/TF-698

### CODE REVIEW

**Comment by eaplatanios** [comment]
@bgogul @dan-zheng I don't think it's a good idea to remove this test. It's quite simple and should be working. If the new toolchain results in incompatible shapes for some reason, we should probably find out why that happens. This kind of operation is common across many models and so existing code may break if this test fails.

**Comment by dan-zheng** [comment]
> @bgogul @dan-zheng I don't think it's a good idea to remove this test. It's quite simple and should be working. If the new toolchain results in incompatible shapes for some reason, we should probably find out why that happens. This kind of operation is common across many models and so existing code may break if this test fails.

I'm investigating the failure now. I haven't narrowed down the cause yet; once I do, I'll revert the `apple/swift` PR that introduced the breakage if an immediate fix isn't obvious.

**Comment by eaplatanios** [comment]
That's great. Thanks Dan!

**Comment by dan-zheng** [comment]
Fixed derivatives of `Tensor.concatenated(with:)` and `Tensor.++` in https://github.com/apple/swift/pull/26448.

**Pull request merged**
