### PR TITLE
Add py3/numpy requirement

### PR DESCRIPTION
**Pull request by texasmichelle**
Add requirement for building swift-apis. This resolves errors like the below:

```
ERROR: Analysis of target '//tensorflow/compiler/tf2xla/xla_tensor:x10' failed; build aborted: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/michellecasbon/repos/tensorflow/texasmichelle/out/libtensorflow-prefix/src/libtensorflow/third_party/py/python_configure.bzl", line 263
		_create_local_python_repository(<1 more arguments>)
	File "/home/michellecasbon/repos/tensorflow/texasmichelle/out/libtensorflow-prefix/src/libtensorflow/third_party/py/python_configure.bzl", line 213, in _create_local_python_repository
		_get_numpy_include(<2 more arguments>)
	File "/home/michellecasbon/repos/tensorflow/texasmichelle/out/libtensorflow-prefix/src/libtensorflow/third_party/py/python_configure.bzl", line 187, in _get_numpy_include
		execute(repository_ctx, <3 more arguments>)
	File "/home/michellecasbon/repos/tensorflow/texasmichelle/out/libtensorflow-prefix/src/libtensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 5.095s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 10 target\
s configured)
```

### CODE REVIEW

**Comment by texasmichelle** [comment]
Is swift-jupyter part of this build? If so, could we rearrange things so that it checks for a compatible python install?

There a bunch of different ways to manage python installations and I'm fine documenting others, pyenv just happens to be my current preference.

**Comment by compnerd** [comment]
No, jupyter is not part of this build - but it is part of the project as a whole.  So you end up with a system with conda _and_ pyenv as python management systems if you blindly start following the documentation.  Personally I think that just having the user manage python is better but thats just me.

**Comment by texasmichelle** [comment]
So you're recommending that we remain unopinionated on python management systems? If so, I'll remove the reference to pyenv

**Comment by compnerd** [comment]
Yeah, I think that remaining unopinionated might be the best choice here - otherwise we need to ensure that we have something which cuts across at least TensorFlow/bazel/jupyter(/Swift/LLVM)

**Pull request merged**
