### PR TITLE
build: use `X10_LIBRARY` to reference the x10 library

### PR DESCRIPTION
**Pull request by compnerd**
This allows explicitly specifying the x10 library rather than a single
tensorflow library which is assumed to be x10.

### CODE REVIEW

**Comment by dabrahams** [comment]
@asuhan plans to test this

**Comment by asuhan** [comment]
@compnerd Still getting the same https://pastebin.com/KXfNRrcE as before. The ops_test executable links to both libtensorflow.so.2 and libx10.so, so the duplication problems persist.

**Comment by pschuh** [comment]
@asuhan Do we have to do the change where tensorflow.so is just a symlink to x10.so in the toolchain first?

**Comment by asuhan** [comment]
@pschuh We do that already without this patch. Not sure what the difference would be in that case.

**Pull request closed without merging**
