### PR TITLE
Add missing tests for XCTestManifests

### PR DESCRIPTION
**Pull request by t-ae**
There's some tests not included in XCTestManifests.swift.
They are not executed on Ubuntu. So CI can miss test failures.

I think it's better to use `swift test --enable-test-discovery` and quit maintaining XCTestManifests manually. What do you think?

### CODE REVIEW

**Comment by rxwei** [comment]
+1 to using test discovery. My impression is that it's still in beta though.

**Comment by saeta** [comment]
Thanks @t-ae for this! Note that there are some environments where test discovery might not be available (e.g. where builds are not done using SwiftPM), so we can't abandon the manual listings yet. :-(

**Comment by Shashi456** [comment]
@saeta @rxwei just a question, I just pulled from master, and swift test doesnt pass anymore. I'm getting this error,
``` 
swift: /swift-base/swift/lib/SILOptimizer/Mandatory/Differentiation.cpp:5246: void (anonymous namespace)::PullbackEmitter::visitApplyInst(swift::ApplyInst *): Assertion `!getActivityInfo().isActive(ai, getIndices())' failed.
Stack dump:
0.      Program arguments: /mnt/g/code/s4tf/usr/bin/swift -frontend -c /mnt/g/code/swift-apis/Tests/TensorFlowTests/ContextTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/CoreTests/UtilitiesTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/Helpers.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/InitializerTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LayerTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorEvaluationTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorExplicitTraceTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorHandleTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorOperationTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorShapeInferenceTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorTFFunctionBuilderTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorTestHelper.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LazyTensorTraceTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/LossTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/OperatorTests/BasicTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/OperatorTests/ComparisonTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/OperatorTests/DatasetTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/OperatorTests/MathTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/OptimizersTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/PRNGTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/RuntimeTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/SequentialTests.swift -primary-file /mnt/g/code/swift-apis/Tests/TensorFlowTests/TensorAutoDiffTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/TensorGroupTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/TensorTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/TrivialModelTests.swift /mnt/g/code/swift-apis/Tests/TensorFlowTests/XCTestManifests.swift -emit-module-path /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug/TensorFlowTests.build/TensorAutoDiffTests~partial.swiftmodule -emit-module-doc-path /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug/TensorFlowTests.build/TensorAutoDiffTests~partial.swiftdoc -emit-dependencies-path /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug/TensorFlowTests.build/TensorAutoDiffTests.d -emit-reference-dependencies-path /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug/TensorFlowTests.build/TensorAutoDiffTests.swiftdeps -target x86_64-unknown-linux -disable-objc-interop -I /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug -enable-testing -g -module-cache-path /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug/ModuleCache -swift-version 4.2 -Onone -D SWIFT_PACKAGE -D DEBUG -color-diagnostics -enable-anonymous-context-mangled-names -parse-as-library -module-name TensorFlowTests -o /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug/TensorFlowTests.build/TensorAutoDiffTests.swift.o -index-store-path /mnt/g/code/swift-apis/.build/x86_64-unknown-linux/debug/index/store -index-system-modules
1.      Swift version 5.1-dev (LLVM 200186e28b, Swift 3374bc7304)
2.      While running pass #2380 SILModuleTransform "Differentiation".
/mnt/g/code/s4tf/usr/bin/swift[0x4641054]
/mnt/g/code/s4tf/usr/bin/swift[0x463ecae]
/mnt/g/code/s4tf/usr/bin/swift[0x4641468]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f9eb15f2890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f9eaf9fee97]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f9eafa00801]
/lib/x86_64-linux-gnu/libc.so.6(+0x3039a)[0x7f9eaf9f039a]
/lib/x86_64-linux-gnu/libc.so.6(+0x30412)[0x7f9eaf9f0412]
/mnt/g/code/s4tf/usr/bin/swift[0xd33503]
/mnt/g/code/s4tf/usr/bin/swift[0xd0f2be]
/mnt/g/code/s4tf/usr/bin/swift[0xcfae86]
/mnt/g/code/s4tf/usr/bin/swift[0xd4c2fb]
/mnt/g/code/s4tf/usr/bin/swift[0xcfdbc7]
/mnt/g/code/s4tf/usr/bin/swift[0xcf5d38]
/mnt/g/code/s4tf/usr/bin/swift[0x963d5f]
/mnt/g/code/s4tf/usr/bin/swift[0x964751]
/mnt/g/code/s4tf/usr/bin/swift[0x553fd8]
/mnt/g/code/s4tf/usr/bin/swift[0x96c78d]
/mnt/g/code/s4tf/usr/bin/swift[0x74b168]
/mnt/g/code/s4tf/usr/bin/swift[0x4d5d6b]
/mnt/g/code/s4tf/usr/bin/swift[0x4d20bd]
/mnt/g/code/s4tf/usr/bin/swift[0x474000]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f9eaf9e1b97]
/mnt/g/code/s4tf/usr/bin/swift[0x473c4a]
```

**Comment by saeta** [comment]
This looks like a crasher in the AD pass... could you bisect `swift-apis` to determine what change might be triggering the crasher? Alternatively, could you investigate trying to minimize a reproducer? (For starters, it appears as if the primary file is `TensorAutoDiffTests.swift`, so that might be a place to start.) Please do put these details in a new JIRA issue on bugs.swift.org. Thanks!

**Comment by Shashi456** [comment]
@saeta i built it on the latest nightly again and i only have one test failing now. 
``` swift
/mnt/g/code/swift-apis/Tests/TensorFlowTests/TensorAutoDiffTests.swift:164: error: 
TensorAutoDiffTests.testTensorInitStacking : XCTAssertEqual failed: ("[1.0, 2.0, 3.0, 4.0, 5.0]")
 is not equal to ("0.0") -

/mnt/g/code/swift-apis/Tests/TensorFlowTests/TensorAutoDiffTests.swift:165: error: 
TensorAutoDiffTests.testTensorInitStacking : XCTAssertEqual failed: ("[ 6.0,  7.0,  8.0,  9.0, 10.0]")
 is not equal to ("0.0") -
```

**Comment by Shashi456** [comment]
cc: @eaplatanios

**Comment by rxwei** [comment]
@Shashi456  https://github.com/apple/swift/pull/26762 already fixed the crasher [TF-653](https://bugs.swift.org/browse/TF-653). You are experiencing it because swift-apis is updated with what would triggered the crash and because your toolchain is not new enough.

**Comment by Shashi456** [comment]
@rxwei yeah I updated the toolchain after that :P, thanks for the clarification. I then immediately mentioned the test error after that.

**Comment by rxwei** [comment]
Could you file a bug for the test errors and describe it in detail?

**Comment by Shashi456** [comment]
@rxwei bug filed at [TF-771](https://bugs.swift.org/browse/TF-771).

**Pull request merged**
