### PR TITLE
Fix RNN gradient accumulation.

### PR DESCRIPTION
**Pull request by Shashi456**
partial fix for #518.

### CODE REVIEW

**Comment by rxwei** [comment]
Could you please add a unit test?

**Comment by Shashi456** [comment]
@rxwei how would a unit test for gradient accumulation look like?

**Comment by rxwei** [comment]
Just add a unit test for `RNN`.

**Comment by eaplatanios** [comment]
You can check whether the gradient of the update matrix is non-zero for
time steps before the last one I believe. The bug should make these
gradients zero and this should be fixed now.

**Comment by rxwei** [comment]
@Shashi456 Did you have a chance to update this PR?

**Comment by Shashi456** [comment]
@rxwei sorry for the delay, I'll write the rnn test in a day or 2.

**Comment by saeta** [comment]
Hi @Shashi456 ! Just following up here; do you think you can add a test or two? Thanks so much for this PR! -Brennan

**Comment by Shashi456** [comment]
@saeta, when we say unit test we mean an rnn gradient test? Sorry for the confusion

**Comment by marcrasi** [comment]
Hi, we'll merge this now to unblock #522. We're still interested in having a test, so I'll create a github issue for that and we can discuss details about the test there.

**Pull request merged**
