### PR TITLE
Minor fix for AD.

### PR DESCRIPTION
**Pull request by eaplatanios**
@rxwei This is based on what you mentioned in [this email thread](https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/a5vaC2GTY_w).

### CODE REVIEW

**Comment by rxwei** [comment]
Thanks!

**Comment by rxwei** [comment]
It's not a bug though. We just need a API that allows you to use any function/property while forcing the derivative to be zero.

**Comment by eaplatanios** [comment]
> It's not a bug though. We just need a API that allows you to use any function/property while forcing the derivative to be zero.

Sorry, the "bug fix" commit was referring to the use of `_TFGetScalarOrDie` in `Math.swift`, which was missing from the previous PR moving stuff over from stdlib. :)

**Comment by rxwei** [comment]
Got it!

**Comment by rxwei** [comment]
Since this doesn't compile with SwiftPM, I'll have to revert it along with #70 to iterate further. Happy to help with resolving the compilation issues!

**Pull request merged**
