### PR TITLE
Remove Comparable conformance of Tensor

### LINKED ISSUE #451: Problem in comparison operators
https://github.com/tensorflow/swift-apis/blob/3629ddc49b706df89f89fa3e92e495e6e3f42332/Sources/TensorFlow/Operators/Comparison.swift#L104-L132

Documentation comments says they compare two tensors "lexicographically".
But it seems the code doing is not lexicographical comparison.

I tried to fix it, but soon got stuck.
In the first place, is lexicographical order defined on tensors?

### PR DESCRIPTION
**Pull request by t-ae**
Resolve #451. 
1. Remove `Comparable` conformance of `Tensor`.
2. Update documentation comments of comparison operators.

### CODE REVIEW

**Comment by rxwei** [comment]
The comparison operators were only added to satisfy `Tensor`'s conformance to `Comparable`. So we should remove these operators as well.

**Comment by rxwei** [comment]
I'd suggest marking those operators deprecated first and with a message that suggests what to use instead.

**Comment by t-ae** [comment]
Added deprecated messages.
Should I move them into BackwardsCompatibility.swift?

**Comment by Shashi456** [comment]
@t-ae yeah that might be a good idea.

**Comment by rxwei** [comment]
Yes. Thanks!

**Pull request merged**
