### PR TITLE
Add OptimizerTests

### PR DESCRIPTION
**Pull request by t-ae**
This PR adds tests for optimizers, mainly for tracking the bug I found in other PR.
https://github.com/tensorflow/swift-apis/pull/683#issuecomment-589523022, https://bugs.swift.org/browse/TF-1178

On macOS all tests pass.
On Linux `testAdaMax` and `testAMSGrad` fail.

### CODE REVIEW

**Comment by saeta** [comment]
Note: fixes #696

**Comment by Shashi456** [comment]
@marcrasi @saeta I had removed `OptimizerTests.swift` in #484, since it was incomplete and also redundantly tested optimizers. Given this PR and that sequential tests fail, #683, Should we consider removing the file and making this file the home for optimizer tests?

**Comment by saeta** [comment]
In order to have [focused orthogonal tests](https://github.com/tensorflow/swift-apis/wiki/Testing#focused-orthogonal-tests), I think we should test the optimizers as @t-ae has done in this PR, and we should test Sequential with a unit test (and a single optimizer) as well. But we should not conflate the tests. Does that make sense @Shashi456 ?

**Comment by marcrasi** [comment]
Hmm, these tests are passing for me on my local Linux machine with the latest nightly builds. Maybe the problem has magically fixed itself since last time we ran the tests, or maybe the problem is platform-dependent enough that my Linux machine does not have the problem. I will now:
* rerun CI, and
* try out these tests on a different linux machine

**Comment by marcrasi** [comment]
Aha, when I run on my linux machine with the older nightly toolchain that existed when we last ran these tests, it does fail. So something has indeed magically fixed the problem! I expect that CI will pass now, and I'll merge these tests as soon as CI does pass so that we prevent the problem from reoccurring. Thanks for these nice orthogonal tests!

**Comment by marcrasi** [comment]
I'm also going to dig around in git history a bit to see if I can find any clue about what broke and what fixed this.

**Pull request merged**
