### PR TITLE
Added support for 'logSumExp'.

### PR DESCRIPTION
**Pull request by eaplatanios**
Depends on #149. @rxwei I was also relying on a general `Tensor.withoutDerivative()` for this. It'd be nice to find a nice way to deal with this situation more generally.

### CODE REVIEW

**Comment by rxwei** [comment]
Could you use the global `Swift.withoutDerivative(at:in:)` for now?

**Comment by eaplatanios** [comment]
I addressed that. It remains to add documentation and tests which I'll do later today.

**Comment by eaplatanios** [comment]
@rxwei I added documentation and tests. The CI tests are running now and so this only requires an approving review.

**Comment by eaplatanios** [comment]
CI tests pass so this is only pending a review.

**Comment by rxwei** [comment]
> @rxwei I was also relying on a general `Tensor.withoutDerivative()` for this. It'd be nice to find a nice way to deal with this situation more generally.

Yeah I saw your use case. I think this justifies having a top-level `withoutDerivative<T>(_ x: T) -> T` identity function.

**Pull request merged**
