### PR TITLE
Minor tweak to allow min and max to be differentiable.

### PR DESCRIPTION
**Pull request by eaplatanios**
@rxwei this is ready to be tested.

### CODE REVIEW

**Comment by Shashi456** [comment]
Thanks a lot for the quick fix @eaplatanios

**Comment by rxwei** [comment]
All tests passed.

**Comment by bgogul** [comment]
> All tests passed.

@rxwei It looks like CI failed?

https://source.cloud.google.com/results/invocations/bbdcc21e-85b1-4a35-a9d9-ba94136e3c64

**Comment by Shashi456** [comment]
@bgogul the CI error is being fixed.

**Comment by bgogul** [comment]
> @bgogul the CI error is being fixed.

Ah.. Thanks, @Shashi456 !

**Comment by rxwei** [comment]
The CI failure is not fixed. It's failure that's only reproducible on Linux or when `-O` is enabled. Filed #161.

**Comment by Shashi456** [comment]
@rxwei some parts of the CI error are triggered by #155

**Pull request merged**
